const placesData = [
  { hebrew: "חשבונאות", english: "accounting" },
  { hebrew: "שדה תעופה", english: "airport" },
  { hebrew: "פארק השעשועים", english: "amusement_park" },
  { hebrew: "גלריית_אמנות", english: "art_gallery" },
  { hebrew: "כַּספּוֹמָט", english: "atm" },
  { hebrew: "מַאֲפִיָה", english: "bakery" },
  { hebrew: "בַּנק", english: "bank" },
  { hebrew: "בַּר", english: "bar" },
  { hebrew: "באולינג", english: "bowling_alley" },
  { hebrew: "תחנת אוטובוס", english: "bus_station" },
  { hebrew: "בֵּית קָפֶה", english: "cafe" },
  { hebrew: "השכרת רכב", english: "car_rental" },
  { hebrew: "מוסך רכב", english: "car_repair" },
  { hebrew: "שטיפת מכוניות", english: "car_wash" },
  { hebrew: "בֵּית קְבָרוֹת", english: "cemetery" },
  { hebrew: "חנות בגדים", english: "clothing_store" },
  { hebrew: "חנות נוחות", english: "convenience_store" },
  { hebrew: "כלבו", english: "department_store" },
  { hebrew: "בֵּית מִרקַחַת", english: "drugstore" },
  { hebrew: "שגרירות", english: "embassy" },
  { hebrew: "תחנת דלק", english: "gas_station" },
  { hebrew: "חדר כושר", english: "gym" },
  { hebrew: "טיפוח_שיער", english: "hair_care" },
  { hebrew: "בית חולים", english: "hospital" },
  { hebrew: "סִפְרִיָה", english: "library" },
  { hebrew: "תחנת_רכבת קלה", english: "light_rail_station" },
  { hebrew: "חנות משקאות", english: "liquor_store" },
  { hebrew: "לִינָה", english: "lodging" },
  { hebrew: "ארוחה_טייק אווי", english: "meal_takeaway" },
  { hebrew: "אולם קולנוע", english: "movie_theater" },
  { hebrew: "מוּזֵיאוֹן", english: "museum" },
  { hebrew: "מועדון לילה", english: "night_club" },
  { hebrew: "פַּארק", english: "park" },
  { hebrew: "חֲנָיָה", english: "parking" },
  { hebrew: "חנות לחיות מחמד", english: "pet_store" },
  { hebrew: "בֵּית מִרקַחַת", english: "pharmacy" },
  { hebrew: "פיזיותרפיסט", english: "physiotherapist" },
  { hebrew: "דואר", english: "post_office" },
  { hebrew: "מִסעָדָה", english: "restaurant" },
  { hebrew: "בית ספר", english: "school" },
  { hebrew: "בית ספר תיכון", english: "secondary_school" },
  { hebrew: "קניון", english: "shopping_mall" },
  { hebrew: "ספָּא", english: "spa" },
  { hebrew: "אִצטַדיוֹן", english: "stadium" },
  { hebrew: "חנות", english: "store" },
  { hebrew: "תחנת רכבת תחתית", english: "subway_station" },
  { hebrew: "סוּפֶּרמַרקֶט", english: "supermarket" },
  { hebrew: "בית כנסת", english: "synagogue" },
  { hebrew: "תחנת מוניות", english: "taxi_stand" },
  { hebrew: "מוקד תיירות", english: "tourist_attraction" },
  { hebrew: "תחנת רכבת", english: "train_station" },
  { hebrew: "תחנת_תחבורה", english: "transit_station" },
  { hebrew: "אוּנִיבֶרְסִיטָה", english: "university" },
  { hebrew: "גַן חַיוֹת", english: "zoo" },
];

export default placesData;
